# Figure out how many metabolic reactions are encoded as "none"
# then drop them from the heart and liver RAS (reaction activity scores)

# Load libraries
library(data.table)
library(dplyr)
library(stringr)

# Read in heart and liver RAS scores generated by Expression2Ras galaxy server
heart_RAS <- fread("/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/heart2_RAS_recon22.txt")
class(heart_RAS) # data.table data.frame
heart_RAS <- as.data.frame(heart_RAS)
class(heart_RAS) # data.frame
heart_RAS[1:5,1:5]
# Check how did fread() read in the cells encoded as "none"
heart_RAS["RE1240C",1:5] # <NA>

# How many metabolic reactions are encoded as "none"?
heart_RAS
class(heart_RAS) # data.frame
heart_RAS <- as.data.frame(heart_RAS)
class(heart_RAS) # data.frame
heart_RAS["RE1240C",1:5] # <NA>
any(is.na(heart_RAS))==TRUE # It doesn't pick up on NA values if the rowname is NA
# Drop rows with NA as rhe rowname
heart2 <- heart_RAS[rowSums(heart_RAS == "None")==0, , drop = FALSE]
heart2["RE1240C",1:5] # <NA>
heart2[8:10,1:5] # <NA>
any(is.na(heart2))==TRUE # It doesn't pick up on NA values if the rowname is NA

# Repeat with liver
liver_RAS <- fread("/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/liver_RAS_Recon22.txt")
class(liver_RAS) # data.table data.frame
liver_RAS <- as.data.frame(liver_RAS)
class(liver_RAS) # data.frame
liver_RAS[1:5,1:5]
# Check how did fread() read in the cells encoded as "none"
liver_RAS["RE1240C",1:5] # <NA>

# How many metabolic reactions are encoded as "none"?
liver_RAS
class(liver_RAS) # data.frame
liver_RAS <- as.data.frame(liver_RAS)
class(liver_RAS) # data.frame
liver_RAS["RE1240C",1:5] # <NA>
any(is.na(liver_RAS))==TRUE # It doesn't pick up on NA values if the rowname is NA
# Drop rows with NA as rhe rowname
liver2 <- liver_RAS[rowSums(liver_RAS == "None")==0, , drop = FALSE]
liver2["RE1240C",1:5] # <NA>
liver2[8:10,1:5] # <NA>
any(is.na(liver2))==TRUE # It doesn't pick up on NA values if the rowname is NA

# Check that equal numbers of rows were dropped in the heart and liver RAS dataframes
dim(heart2)==dim(liver2) # TRUE TRUE
dim(heart2) # 4741 149
dim(liver2) # 4741 149

# Sort the columns to be in the same order
# The sample names will only be partial matches because the last 5 characters indicate
# organ that was sampled
heart3 <- heart2 # make a copy dataframe
heart3[unlist(lapply(gsub("\\d+", "", colnames(liver2[2:ncol(liver2)]), function(x) grep(x, colnames(heart3)))))]

# Create a vector of strings of the sample IDs from the column names
heart_sample_id <- str_sub(colnames(heart2), start=1L, end=10L)
liver_sample_id <- str_sub(colnames(liver2), start=1L, end=10L)

# Sort the vector of sample IDs to be in the same order
heart_sampleID_sorted <- heart_sample_id[order(heart_sample_id)]
liver_sampleID_sorted <- liver_sample_id[order(heart_sample_id)]

# Check the vectors are identical
all.equal(heart_sampleID_sorted, liver_sampleID_sorted) # TRUE

# Move the "reactions" column to the front
heart_colnames <- c(heart_sampleID_sorted[149], heart_sampleID_sorted)
heart_colnames <- heart_colnames[-length(heart_colnames)]
length(heart_colnames)==ncol(heart2) # TRUE

liver_colnames <- c(liver_sampleID_sorted[149], liver_sampleID_sorted)
liver_colnames <- liver_colnames[-length(liver_colnames)]
length(liver_colnames)==ncol(liver2) # TRUE

# Check the vectors are identical
all.equal(heart_colnames, liver_colnames) # TRUE

# Replace the original column names with the sample IDs only
# I am guessing the samples need to be in the same order for MaREA
class(heart2) # data.frame
setDT(heart2)
class(heart2) # data.table data.frame
idx <- match(heart_colnames, liver_colnames)
setcolorder(heart2, match(seq_along(heart2), idx))
setcolorder(liver2, match(seq_along(liver2), idx))
head(colnames(liver2));head(colnames(heart2)) # Sample IDs are in the right order
tail(colnames(liver2));tail(colnames(heart2)) # Sample IDs are in the right order

# Write to file
liver_RAS <- write.table(liver2, "/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/liver_RAS_recon22_complete_cases_only.tsv", quote=FALSE, sep='\t', col.names = NA)
heart_RAS <- write.table(heart2, "/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/heart_RAS_recon22_complete_cases_only.tsv", quote=FALSE, sep='\t', col.names = NA)

# Write a small subset to file
small_heart <- heart2[1:10,1:10]
small_liver <- liver2[1:10,1:10]
small_heart 
small_liver

# Write to file
small_liver_RAS <- write.table(small_liver, "/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/small_liver_RAS_recon22_complete_cases_only.tsv", quote=FALSE, sep='\t', col.names = NA)
small_heart_RAS <- write.table(small_heart, "/scratch/mjpete11/mitochondrial_paralogs/linear_models/data/data/small_heart_RAS_recon22_complete_cases_only.tsv", quote=FALSE, sep='\t', col.names = NA)
